CREATE DATABASE CALCULATION;

USE CALCULATION;

CREATE TABLE user (
  USERNAME VARCHAR(30) NOT NULL,
  PASSWORD TEXT NOT NULL,
  primary KEY (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE history (
  ID int(20) NOT NULL AUTO_INCREMENT,
  CONTENT TEXT NOT NULL,
  DATE date NOT NULL,
  created_by VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (CREATED_BY) REFERENCES user(USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;